name: Deploy
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
      - live
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v2
        with:
          node-version: '16.x'
          registry-url: 'https://registry.npmjs.org'
      - name: Run tests
        run: |
          npm install
          npm run deploy-test
          
          
      - run: npm ci
      - run: npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          
      - uses: codecov/codecov-action@v1
        with:
          file: coverage/*.json
          fail_ci_if_error: true
